# ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
# Makefile pel tunel amb reflexi¢ raytracejat.
# ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

# ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

#DEBUG = 1 
INCDIR = $(TDLPATH)\h
LIBDIR = $(TDLPATH)\lib

!ifdef DEBUG

CFLAGS = -4r -hw -db -d2 -fpi87 -fp3 -i$(INCDIR) -mf -w5 -ze -zp4 -zdp -zl
#AFLAGS = /mx /m2 /q /zi
AFLAGS = -f obj
LFLAGS = system DarkX
#debug all

!else

#CFLAGS = -5r -fpi87 -fp5 -i$(INCDIR) -mf -otexan -w5 -ze -zp4 -zdp -s
CFLAGS = -4r -fpi87 -fp3 -i$(INCDIR) -mf -w5 -ze -zdp -zl
#AFLAGS = /mx /m2 /q
AFLAGS = -f obj
LFLAGS = system DarkX

!endif

.asm.obj:
        tasm $(AFLAGS) $?
.c.obj:
        wcc386 $(CFLAGS) $?
.cpp.obj:
        wpp386 $(CFLAGS) $?

# ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

all: test.exe

test.obj: test.cpp $(INCDIR)\tdl.h

test.exe: test.obj $(LIBDIR)\tdl.lib
        wlink $(LFLAGS) file $(LIBDIR)\c0tt, $(LIBDIR)\wpp, test library $(LIBDIR)\tdl.lib name test

