#DEBUG = 1 
INCDIR = $(TDLPATH)\h
LIBDIR = $(TDLPATH)\lib

!ifdef DEBUG

CFLAGS = -4r -hw -db -d2 -fpi87 -fp3 -i$(INCDIR) -mf -w5 -ze -zp4 -zdp
AFLAGS = -f obj
LFLAGS = system DarkX

!else

CFLAGS = -4r -fpi87 -fp3 -i$(INCDIR) -mf -w5 -ze -zdp -zl
AFLAGS = -f obj
LFLAGS = system DarkX

!endif

.asm.obj:
        tasm $(AFLAGS) $?
.c.obj:
        wcc386 $(CFLAGS) $?
.cpp.obj:
        wpp386 $(CFLAGS) $?

all: example.exe

example.obj: example.cpp $(INCDIR)\tdl.h

example.exe: example.obj $(LIBDIR)\tdl.lib
		wlink $(LFLAGS) file $(LIBDIR)\c0tt, $(LIBDIR)\wpp, example library $(LIBDIR)\tdl.lib name example
