# ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ
# Makefile pel tunel amb reflexi¢ raytracejat.
# ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

# ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

#DEBUG = 1 
INCDIR = $(TDLPATH)\h
LIBDIR = $(TDLPATH)\lib

!ifdef DEBUG

CFLAGS = -4r -hw -db -d2 -fpi87 -fp3 -i$(INCDIR) -mf -w5 -ze -zp4 -zdp -xs
AFLAGS = -f obj
LFLAGS = system DarkX

!else

CFLAGS = -4r -fpi87 -fp3 -i$(INCDIR) -mf -w5 -ze -zdp -d2 -xs
AFLAGS = -f obj
LFLAGS = system DarkX

!endif

.asm.obj:
        tasm $(AFLAGS) $?
.c.obj:
        wcc386 $(CFLAGS) $?
.cpp.obj:
        wpp386 $(CFLAGS) $?

# ÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄÄ

all: play.exe

play.obj: play.cpp $(INCDIR)\tdl.h

play.exe: play.obj $(LIBDIR)\tdl.lib
        wlink $(LFLAGS) file $(LIBDIR)\c0tt, $(LIBDIR)\wpp, play library $(LIBDIR)\tdl.lib name play

